Copy over from trunk. 	Extend pmacro language, add testsuite. 	* Makefile.am (SUBDIRS): Add testsuite. 	* Makefile.in: Regenerate. 	* configure.in (AC_OUTPUT): Create testsuite/Makefile, 	testsuite/test-utils.sh. 	* configure: Regenerate. 	* dev.scm (cload): Handle testsuite app. 	(load-testsuite): New function. 	* pmacros.scm: (-pmacro-debug?): New global. 	(-smacro-table): New global. 	(-smacro-lookup, -smacro-set!): New functions. 	(-pmacro-make): New argument `syntactic-form?', all callers updated. 	(-pmacro-syntactic-form?): New function. 	(-pmacro-expected-number, -pmacro-verify-number): New functions. 	(-pmacro-expected-integer, -pmacro-verify-integer): New functions. 	(-pmacro-expected-non-negative-integer): New function. 	(-pmacro-verify-non-negative-integer): New function. 	(-pmacro-expand-expr-list): New function. 	(-pmacro-process-args-1): Renamed from -pmacro-process-args. 	(-pmacro-process-args): Renamed from -pmacro-invoke. 	(-pmacro-apply, -smacro-apply): New functions. 	(-pmacro-expand): Rewrite syntactic form processing. 	(-pmacro-build-lambda): Reformat. 	(define-pmacro): Watch for more errors in definition. 	(pmacro-debug): New function. 	(pmacro-trace): Set/reset -pmacro-debug?. 	(all existing builtin pmacro helpers): Rename to -pmacro-builtin-foo. 	(-pmacro-builtin-substring): Fix.  Add support for `end' marker. 	(-pmacro-builtin-for-each, et.al.): New helpers for .for-each, .let, 	.if, .case, .cond, .begin, .print, .dump, .error, .list, .ref, 	.length, .replicate, .equals, .and, .or, .not, .eq, .ne, .lt, .gt, 	.le, .ge, .add, .sub, .mul, .div, .rem, .sll, .srl, .sra, .bitand, 	.bitor, .bitxor, bitinv, .car, .cdr, .caar, .cadr, .cdar, .cddr. 	(pmacros-init!): Initialize -smacro-table. 	Rewrite pmacro initialization. 	* read.scm (reader-process-expanded): Renamed from 	-reader-process-expanded.  All callers updated. 	Recognize () as a no-op. 	(cpu-load): Tweak logging messages. 	* utils.scm (message): Add comment. 	* cpu/play.cpu: Add some instructions to play with .let. 	* doc/cgenint.texi: Move some debugging related docs to here from 	cgen.texi. 	* doc/pmacros.texi: Reorganize.  Add docs for new builtin pmacros. 	* testsuite/Makefile.am: New file. 	* testsuite/Makefile.in: New file. 	* testsuite/test-utils.sh.in: New file. 	* testsuite/run-tests.sh: New file. 	* testsuite/testsuite.cpu: New file. 	* testsuite/pmacros-1.test: New file.

diff --git a/cgen/testsuite/test-utils.sh.in b/cgen/testsuite/test-utils.sh.in
--- a/cgen/testsuite/test-utils.sh.in
+++ b/cgen/testsuite/test-utils.sh.in
@@ -31,26 +31,17 @@ rm -f ${tmp_match} ${tmp_expr}
 
 exit_code=0
 
-# Invoke this to run cgen.
-# Usage: run_cgen [-f] cpu-file-path
-# -f: cgen is expected to fail (useful for testing error handling)
-
 run_cgen() {
-    expect_fail=false
-    [ "$1" == "-f" ] && { expect_fail=true ; shift ; }
-
-    [ $# -ne 1 ] && { echo "missing cpu_file" >&2 ; exit 1 ; }
+    [ $# == 1 ] || { echo "missing cpu_file" >&2 ; exit 1 ; }
     cpu_file=$1
 
-    if ${GUILE} ${GUILEFLAGS} ${cgendir}/cgen-testsuite.scm \
+    if ! ${GUILE} ${GUILEFLAGS} ${cgendir}/cgen-testsuite.scm \
 	-s ${cgendir} \
 	-b ${CGENFLAGS} \
 	-a ${cpu_file} \
 	-T ${cgen_output_file} >& ${test_output_file}
     then
-	${expect_fail} && { fail "${test} run of cgen expected to fail" ; }
-    else
-	${expect_fail} || { fail "${test} run of cgen" ; }
+	fail "${test} run of cgen"
     fi
 }
 
@@ -59,7 +50,7 @@ post_process() {
 
     if grep -q FAIL $file
     then
-	fail "In test output:"
+	fail "FAIL found in test output:"
 	grep FAIL $file
     fi
 
